version: '3'
services:
  discovery:
    build: discovery-server/.
    ports:
      - "8761:8761"
  movie-catalog:
    build: movie-catalog-service/.
    ports:
      - "8081:8081"
  movie-info:
    build: movie-info-service/.
    ports:
      - "8082:8082"
  movie-data:
    build: ratings-data-service/.
    ports:
      - "8083:8083"
  