version: '3'
services:
  discovery:
    image: discoveryservice
    expose:
      - "8761"
    networks:
      - internal
  movie-catalog:
    image: movie-catalog-service
    ports:
      - "8081:8081"
    networks:
      - internal
  movie-info:
    image: movie-info-service
    expose:
      - "8082"
    networks:
      - internal
  movie-data:
    image: ratings-data-service
    expose:
      - "8083"
    networks:
      - internal
networks:
  internal:
    driver: bridge